// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5_dOmowQ4OhyBEV1487pE0tl_aKAaoVc',
    appId: '1:133888042850:web:a653bb3df40822a7ba2e3b',
    messagingSenderId: '133888042850',
    projectId: 'k9nix-kaisaer',
    authDomain: 'k9nix-kaisaer.firebaseapp.com',
    storageBucket: 'k9nix-kaisaer.appspot.com',
    measurementId: 'G-XQSB5BL750',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkUuMqiP_cHcTfT-VDG5zwzjkr03h0Jw4',
    appId: '1:133888042850:android:46b74905e1d5aab8ba2e3b',
    messagingSenderId: '133888042850',
    projectId: 'k9nix-kaisaer',
    storageBucket: 'k9nix-kaisaer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDniB0aYl9kn6m8I_RGaowxeGLdth1Ecas',
    appId: '1:133888042850:ios:c6fcab3173dd3c8dba2e3b',
    messagingSenderId: '133888042850',
    projectId: 'k9nix-kaisaer',
    storageBucket: 'k9nix-kaisaer.appspot.com',
    iosClientId: '133888042850-17gnt6g0nfk0udpi4f7uh4pd141v5f5u.apps.googleusercontent.com',
    iosBundleId: 'com.kaisaer.k9nix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDniB0aYl9kn6m8I_RGaowxeGLdth1Ecas',
    appId: '1:133888042850:ios:c6fcab3173dd3c8dba2e3b',
    messagingSenderId: '133888042850',
    projectId: 'k9nix-kaisaer',
    storageBucket: 'k9nix-kaisaer.appspot.com',
    iosClientId: '133888042850-17gnt6g0nfk0udpi4f7uh4pd141v5f5u.apps.googleusercontent.com',
    iosBundleId: 'com.kaisaer.k9nix',
  );
}
